
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author julieta
 */
public class CongruencialMultiplicativo extends javax.swing.JFrame {

    private Generador g;

    /**
     * Creates new form CongruencialMixto
     */
    public CongruencialMultiplicativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_atras = new javax.swing.JButton();
        btn_generar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        btn_siguiente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_x = new javax.swing.JTextField();
        txt_g = new javax.swing.JTextField();
        txt_k = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_m = new javax.swing.JTextField();
        txt_a = new javax.swing.JTextField();
        rbt_a = new javax.swing.JRadioButton();
        rbt_b = new javax.swing.JRadioButton();

        buttonGroup1.add(rbt_a);
        buttonGroup1.add(rbt_b);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_atras.setText("Atrás");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        btn_generar.setText("Generar");
        btn_generar.setPreferredSize(new java.awt.Dimension(75, 50));
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jScrollPane1.setViewportView(lista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 200, 290));

        jLabel7.setText("k:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel5.setText("g:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Números Aleatorios:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 150, -1));

        jLabel2.setText("x:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Elegir Constantes:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 10, 400));

        txt_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_xActionPerformed(evt);
            }
        });
        txt_x.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_xKeyTyped(evt);
            }
        });
        getContentPane().add(txt_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 30, -1));

        txt_g.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_gFocusLost(evt);
            }
        });
        txt_g.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_gKeyTyped(evt);
            }
        });
        getContentPane().add(txt_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 30, -1));

        txt_k.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_kFocusLost(evt);
            }
        });
        txt_k.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kKeyTyped(evt);
            }
        });
        getContentPane().add(txt_k, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 30, -1));

        jLabel6.setText("m:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel8.setText("a:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txt_m.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_mFocusLost(evt);
            }
        });
        txt_m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_mKeyTyped(evt);
            }
        });
        getContentPane().add(txt_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 30, -1));

        txt_a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_aFocusLost(evt);
            }
        });
        txt_a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_aKeyTyped(evt);
            }
        });
        getContentPane().add(txt_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, -1));

        rbt_a.setText(" a = 3 + 8k");
        rbt_a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rbt_aFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rbt_aFocusLost(evt);
            }
        });
        rbt_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_aActionPerformed(evt);
            }
        });
        rbt_a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbt_aKeyPressed(evt);
            }
        });
        getContentPane().add(rbt_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        rbt_b.setText("a = 5 + 8k");
        rbt_b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rbt_bFocusLost(evt);
            }
        });
        getContentPane().add(rbt_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed

        if (!this.validar()) {
        int semilla = Integer.parseInt(txt_x.getText());

            g = new Generador(Integer.parseInt(txt_a.getText()), Integer.parseInt(txt_m.getText()), Integer.parseInt(txt_x.getText()));
            lista.setListData(g.logicaMultiplicativo(20, semilla).toArray());
            //crea generador con todos los datos que se ingresaron y el metodo multiplicativo devuelve un ArrayList que se asigna a la lista de la ventana
        }
    }//GEN-LAST:event_btn_generarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        if(!validar()){
        lista.setListData(g.logicaMultiplicativo(g.getLista().size() + 1, g.getSemilla()).toArray());
        // multiplicativo retorna una lista con n+1 valores y usa como semilla el ultimo valor guardado en la semilla
        }
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void txt_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_xActionPerformed

    private void txt_xKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_xKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (a < '0' || a > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_xKeyTyped

    private void txt_gKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_gKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (a < '0' || a > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_gKeyTyped

    private void txt_kKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if (a < '0' || a > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_kKeyTyped

    private void txt_mKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_mKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mKeyTyped

    private void txt_aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_aKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aKeyTyped

    private void txt_mFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mFocusLost
        // TODO add your handling code here:
        if (!txt_m.getText().equals("")) {
            txt_g.setText("");
            txt_g.setEnabled(false);
        } else {
            txt_g.setText("");
            txt_g.setEnabled(true);
        }

    }//GEN-LAST:event_txt_mFocusLost

    private void txt_aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_aFocusLost
        // TODO add your handling code here:
        if (!txt_a.getText().equals("")) {
            txt_k.setText("");
            txt_k.setEnabled(false);
            rbt_a.setEnabled(false);
            rbt_b.setEnabled(false);
        } else {
            txt_k.setText("");
            txt_k.setEnabled(true);
              rbt_a.setEnabled(true);
            rbt_b.setEnabled(true);
            
        }
    }//GEN-LAST:event_txt_aFocusLost

    private void txt_gFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_gFocusLost
        // TODO add your handling code here:
        if (!txt_g.getText().equals("")) {
            int exponente = Integer.parseInt(txt_g.getText());
            int numero = (int) Math.pow(2, exponente);
            String a = Integer.toString(numero);
            txt_m.setText(a);
        }
    }//GEN-LAST:event_txt_gFocusLost

    private void txt_kFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_kFocusLost
        // TODO add your handling code here:
        if (rbt_a.isSelected()) {
            int numero = (3 + 8 * (Integer.parseInt(txt_k.getText())));
            String a = Integer.toString(numero);
            txt_a.setText(a);
        }
        if (rbt_b.isSelected()) {
            int numero = (5 + 8 * (Integer.parseInt(txt_k.getText())));
            String a = Integer.toString(numero);
            txt_a.setText(a);
        }

    }//GEN-LAST:event_txt_kFocusLost

    private void rbt_aKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbt_aKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbt_aKeyPressed

    private void rbt_aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbt_aFocusLost
        // TODO add your handling code here:
        if (rbt_a.isSelected() && !txt_k.getText().equals("")) {
            int numero = (3 + 8 * (Integer.parseInt(txt_k.getText())));
            String a = Integer.toString(numero);
            txt_a.setText(a);
        }


    }//GEN-LAST:event_rbt_aFocusLost

    private void rbt_aFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbt_aFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_aFocusGained

    private void rbt_bFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rbt_bFocusLost
        // TODO add your handling code here:
        if (rbt_b.isSelected() && !txt_k.getText().equals("")) {
            int numero = (5 + 8 * (Integer.parseInt(txt_k.getText())));
            String a = Integer.toString(numero);
            txt_a.setText(a);
        }

    }//GEN-LAST:event_rbt_bFocusLost

    private void rbt_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_aActionPerformed

    private boolean validar() {
        boolean ban = false;
        if (txt_a.getText().equals("") || txt_x.getText().equals("") || txt_m.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe completar algunas constantes");
            ban = true;
        }
        if (txt_a.getText().equals("0") || txt_x.getText().equals("0") || txt_m.getText().equals("0") || txt_k.getText().equals("0") || txt_g.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Las constantes deben ser enteras positivas");
            ban = true;
        }
        return ban;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongruencialMultiplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongruencialMultiplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongruencialMultiplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongruencialMultiplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CongruencialMultiplicativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_generar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lista;
    private javax.swing.JRadioButton rbt_a;
    private javax.swing.JRadioButton rbt_b;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_g;
    private javax.swing.JTextField txt_k;
    private javax.swing.JTextField txt_m;
    private javax.swing.JTextField txt_x;
    // End of variables declaration//GEN-END:variables
}
